In [1]:
"""importar librerias"""
"""libreria para uso de arreglos"""
import numpy as np
"""Libreria para la clasificacion e importacion de data"""
import sklearn  
"""para traer los set de datos"""
from sklearn.datasets import load_iris 
"""para dividir la data en set de entrenamiento y set de testing"""
from sklearn.model_selection import train_test_split 

In [2]:
"""creamos una variable llamada iris para traer todo el set de datos"""
iris=load_iris()

In [3]:
type(iris)

sklearn.utils.Bunch

In [4]:
"""arreglo matriz con 4 dimensiones"""
iris.keys()


dict_keys(['feature_names', 'data', 'target_names', 'target', 'DESCR'])

In [5]:
"""cada reglon es un flor, cada columna es una medicion"""
iris['data']


array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [6]:
"""encontramos cada una de las clasificaciones de las flores """
iris['target_names']


array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [7]:
"""reglones correspondientes cada uno de la data """
"""siempre vamos a convertir la data en numeros"""
iris['target']

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [8]:
"""nombre de cada uno de las mediciones"""
iris['feature_names']

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [9]:
"""uso de la funcion para separar la data para entrenamiento y testing"""
"""los parametros que recibe la funcion son las caracteristicas/data y las etiquetas/target"""

X_train,X_test,y_train,y_test=train_test_split(iris['data'],iris['target'])

In [10]:
"""indica que datos tenemos para entrenar, en este caso una matriz de 112 flores con sus mediciones"""
X_train.shape

(112, 4)

In [11]:
"""vector de 112, etiquetas correspondientes a cada elemento de X Cada una de las clasificaciones"""
y_train.shape

(112,)

In [12]:
"""importacion del clasificador, este funciona con cada nuevo punto dando un valor similar a lo de sus K vecinos cercanos """
from sklearn.neighbors import KNeighborsClassifier

In [13]:
knn=KNeighborsClassifier(n_neighbors = 2)

In [14]:
"""sobre la misma variable le damos la funcion de fit que sirve para entrenarlo"""
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
           metric_params=None, n_jobs=1, n_neighbors=2, p=2,
           weights='uniform')

In [15]:
"""funcion para ver que tan bien aprendio el algoritmo"""
"""la habilidad para predecir cambia de acuerdo al valor de la variable n_neighbors"""
knn.score(X_test,y_test)

0.9210526315789473

In [16]:
"""por ejemplo tenemos 4 mediciones y le pedimos al sistema que nos entregue a que clasificacion pertenece"""

knn.predict([[1.2,3.4,5.6,1.1]])

array([1])

In [17]:
"""de acuerdo al resultado del arreglo vemos a que etiqueta pertecene, en este caso el valor es 1"""
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')